### ISSUE TITLE
No application 'Macro' for extension 

### ISSUE THREAD

**Issue by blacksocket** [bobbyd01001/VoIP-Deployment#1]
Hello,

First of all many thanks for the great script! I installed the freepbx successfully but when configured extentions and my softphone to be able to call I am getting below error. Do you know what is wrong ? 

I am using Debian 10 Buster:
Linux freepbx 4.19.0-20-cloud-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux

My registered sofphones:
Name/username             Host                                    Dyn Forcerport Comedia    ACL Port     Status      Description
703/703                   31.0.32.xxx                              D  Yes        Yes         A  19977    OK (101 ms)
704/704                   192.168.1.xxx                           D  Yes        Yes         A  53888    OK (109 ms)

When try to call from sofphone internal network connected numer 703 to internal network connected softphone 704 i am getting the bellow error:

[2022-05-20 15:19:17] WARNING[1230][C-0000004c]: pbx.c:2925 pbx_extension_helper: No application 'Macro' for extension (from-internal, 703, 3)
  == Spawn extension (from-internal, 703, 3) exited non-zero on 'SIP/704-0000004b'
[2022-05-20 15:19:17] WARNING[1230][C-0000004c]: pbx.c:2925 pbx_extension_helper: No application 'Macro' for extension (from-internal, h, 1)
  == Spawn extension (from-internal, h, 1) exited non-zero on 'SIP/704-0000004b'
[

During the installation process visible on the screenshots here https://techviewleo.com/install-asterisk-with-freepbx-on-debian/
There were no module called app_macro to add during the build process:

![image](https://user-images.githubusercontent.com/13651344/169566541-1e3a5700-205f-4ce3-b5fe-3ad2f64640d2.png)

Similar issue here: https://community.freepbx.org/t/cant-make-internal-calls/70547

**Comment by bobbyd01001** [comment]
Sounds like you may have not built asterisk to include the app_macro
module. Try running make menuselect again, making sure you select that
module. I also have some videos on my YouTube channel on installing freepbx
also.

https://www.youtube.com/c/BeawitConsultingLLC

Who you BeawIT
www.beawit.net

**Comment by blacksocket** [comment]
Sorry I didn't scroll it down because though this is only one page of modules ;-) 
Many thanks for your help!
